quarkus.index-dependency.rimfrost-adapter-arbetsgivare.group-id=se.fk.rimfrost.adapter.arbetsgivare
quarkus.index-dependency.rimfrost-adapter-arbetsgivare.artifact-id=rimfrost-adapter-arbetsgivare
quarkus.index-dependency.rimfrost-adapter-folkbokford.group-id=se.fk.rimfrost.adapter.folkbokford
quarkus.index-dependency.rimfrost-adapter-folkbokford.artifact-id=rimfrost-adapter-folkbokford
quarkus.index-dependency.rimfrost-adapter-individ.group-id=se.fk.rimfrost.adapter.individ
quarkus.index-dependency.rimfrost-adapter-individ.artifact-id=rimfrost-adapter-individ
quarkus.index-dependency.rimfrost-framework-regel-maskinell.group-id=se.fk.rimfrost.framework.regel.maskinell
quarkus.index-dependency.rimfrost-framework-regel-maskinell.artifact-id=rimfrost-framework-regel-maskinell
quarkus.index-dependency.rimfrost-framework-uppgift-status-provider.group-id=se.fk.rimfrost.framework.uppgiftstatusprovider
quarkus.index-dependency.rimfrost-framework-uppgift-status-provider.artifact-id=rimfrost-framework-uppgift-status-provider

# Container image configuration
quarkus.container-image.name=rimfrost-regel-rtf-maskinell

# Kafka configuration
kafka.source=RegelRtfMaskinell

#Incoming
mp.messaging.incoming.regel-requests.topic=rtf-maskinell-requests

#Outgoing
mp.messaging.outgoing.regel-responses.topic=rtf-maskinell-responses


# REST configuration
%dev.folkbokford.api.base-url=http://localhost:8080
%dev.arbetsgivare.api.base-url=http://localhost:8080
%dev.individ.api.base-url=http://localhost:8080
%dev.handlaggning.api.base-url=http://localhost:8080

folkbokford.api.base-url=http://rimfrost-k8s-folkbokford:8080
arbetsgivare.api.base-url=http://rimfrost-k8s-arbetsgivare:8080
individ.api.base-url=http://rimfrost-k8s-individ:8080
handlaggning.api.base-url=http://rimfrost-k8s-handlaggning:8080