package se.fk.github.maskinellregelratttillforsakring.logic;

public class RegelFelkod
{
   public final static String RTF_MASKINELL_FOLKBOKFORING_READ_ERROR = "RTF_MASKINELL_FOLKBOKFORING_READ_ERROR";
   public final static String RTF_MASKINELL_ARBETSGIVARE_READ_ERROR = "RTF_MASKINELL_ARBETSGIVARE_READ_ERROR";
   public final static String RTF_MASKINELL_FOLKBOKFORING_UNDERLAG_CREATION_FAILURE = "RTF_MASKINELL_FOLKBOKFORING_UNDERLAG_CREATION_FAILURE";
   public final static String RTF_MASKINELL_ARBETSGIVARE_UNDERLAG_CREATION_FAILURE = "RTF_MASKINELL_ARBETSGIVARE_UNDERLAG_CREATION_FAILURE";
}
